apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-synergy
  description: Inner Source hub for your organization.
  tags:
    - react
    - nodejs
    - typescript
  annotations:
    github.com/project-slug: jiteshy/backstage-plugin-synergy
spec:
  type: website
  lifecycle: production
  owner: user:default/jiteshy
